[package]
name = "project_00005_00001_hello_world"
version = "0.1.0"
authors = ["MRW Neundorf <ninevillage@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
