[package]
name = "project_00300_leptos_hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.14", features = ["csr", "nightly"] }
